### ISSUE TITLE
Save things on Flutter side

### ISSUE THREAD

**Issue by justinmoon** [futurepaul/fluttermint#7]
IIRC there was some api for storing "settings" type data that we could use? @futurepaul 

The main one we need to save right now is `client.json` containing all information needed to talk to the federation.

But I think there will be more user preferences (e.g. language, do they prefer BTC or sats, etc)

**Comment by futurepaul** [comment]
here's my example of saving preferences in pln... I think this partly exists in fluttermint but it's not as fully wired up: https://github.com/BitcoinDevShop/pln/blob/master/mobile/lib/data/prefs.dart

it's a keyvalue store so you can add as many keys + values as you want just will have to write setter / getter functions (and make prefs a more complicated object rather than a single string)

it can be consumed from other riverpod providers like this: https://github.com/BitcoinDevShop/pln/blob/master/mobile/lib/grpc.dart#L21

and it's written to it here: https://github.com/BitcoinDevShop/pln/blob/master/mobile/lib/screens/welcome.dart#L21

in fluttermint we actually initialize prefs right now but don't do anything with it I guess? https://github.com/futurepaul/fluttermint/blob/master/lib/main.dart#L20
